apiVersion: v1
kind: Service
metadata:
  name: kube-project
  labels:
    app: project_grocery
  namespace: kube_groc_proj
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: project_grocery
    